const selectOptions = {
  price: [
    { value: '0', label: 'Any' },
    { value: '1000', label: '$1,000' },
    { value: '1500', label: '$1,500' },
    { value: '2000', label: '$2,000' },
    { value: '2500', label: '$2,500' },
    { value: '3000', label: '$3,000' },
    { value: '4000', label: '$4,000' },
    { value: '5000', label: '$5,000' },
  ],
  motor: [
    { value: '0', label: 'Any' },
    { value: '250', label: '250W' },
    { value: '500', label: '500W' },
    { value: '750', label: '750W' },
    { value: '1000', label: '1,000W' },
    { value: '1500', label: '1,500W' },
    { value: '2000', label: '2,000W' },
    { value: '3000', label: '3,000W' },
    { value: '5000', label: '5,000W' },
  ],
  battery: [
    { value: '0', label: 'Any' },
    { value: '5', label: '5Ah' },
    { value: '10', label: '10Ah' },
    { value: '15', label: '15Ah' },
    { value: '20', label: '20Ah' },
    { value: '25', label: '25Ah' },
    { value: '30', label: '30Ah' },
  ],
  range: [
    { value: '0', label: 'Any' },
    { value: '20', label: '20 miles' },
    { value: '30', label: '30 miles' },
    { value: '40', label: '40 miles' },
    { value: '50', label: '50 miles' },
    { value: '60', label: '60 miles' },
    { value: '70', label: '70 miles' },
  ],
  voltage: [
    { value: '0', label: 'Any' },
    { value: '36', label: '36V' },
    { value: '48', label: '48V' },
    { value: '52', label: '52V' },
  ],
  top_speed: [
    { value: '0', label: 'Any' },
    { value: '15', label: '15 mph' },
    { value: '20', label: '20 mph' },
    { value: '25', label: '25 mph' },
    { value: '30', label: '30 mph' },
    { value: '35', label: '35 mph' },
    { value: '40', label: '40 mph' },
  ],
  suspension: [
    { value: '0', label: 'Any' },
    { value: 'none', label: 'None' },
    { value: 'front', label: 'Front' },
    { value: 'rear', label: 'Rear' },
    { value: 'full', label: 'Full' },
  ],
  motor_type: [
    { value: '0', label: 'Any' },
    { value: 'Front Hub', label: 'Front Hub' },
    { value: 'Rear Hub', label: 'Rear Hub' },
    { value: 'Dual Hub', label: 'Dual Hub' },
    { value: 'Mid Drive', label: 'Mid Drive' },
  ],
};

export default selectOptions;
